### ISSUE TITLE
Computing this.player.getCurrentTime()

### ISSUE THREAD

**Issue by sergiocastrovale** [anteriovieira/vue-youtube#10]
Hi, thanks a lot for this wrapper for the Youtube API. 

I'm having some trouble figuring out how to display a timestamp in my UI that updates as the video is playing (00:01, ...), because using `setTimeout` doesn't work due to `this.player.getCurrentTime()` being a Promise.

Any idea on how to do this?

**Comment by sergiocastrovale** [comment]
@anteriovieira that worked perfectly. Thanks a lot!

**Comment by thebilljustin** [comment]
Hi. Im getting 'Cannot read property 'youtube' of undefined'

**Comment by TitanFighter** [comment]
How `this.$refs` look like?

**Comment by thebilljustin** [comment]
> How `console.log(this.$refs)` look like?

earlier it returns as undefined. its working now. thanks
