### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by Demy** [anteriovieira/vue-youtube#13]
Embedding video to the page causes this error in the console:
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin (*host name*)`

You can even see this error in the console on the demo page of the plugin.

**Comment by TitanFighter** [comment]
@Demy , Turn off `AddBlock`

**Comment by digord** [comment]
Same problem and I don't have Adblock

**Comment by levon89** [comment]
Problem caused , because first need to show player container. After that load Video id

**Comment by kanapka94** [comment]
I have the same error and think that [this answer](https://github.com/kaorun343/vue-youtube-embed/issues/29#issuecomment-416191955) can be to the question.

**Comment by aglio** [comment]
I have same issue. But I gave up fixing this problem. This error seems to be caused by [YouTube IFrame Player API](https://developers.google.com/youtube/iframe_api_reference) (YIPA).
I got a same error when I tried this YIPA sample code. Therefore, I think that this error can not be fixed at present.
FYI, https://github.com/videojs/videojs-youtube/issues/67

**Comment by TheJadeEmperor** [comment]
> @Demy , Turn off `AdBlock`

Literally the dumbest comment made in Github. Turning off adblock does ABSOLUTELY NOTHING. Knowing that, I turned off Adblock anyways, and confirmed that it did ABSOLUTELY nothing. This is a place for developers, not dickheads, so get a life and get the f**k out of here.

**Comment by TitanFighter** [comment]
@TheJadeEmperor for your information, I had the same problem and before I posted it I checked multiply times that turning off AdBlock solved issue, but later, for some reason the issue came back.


> This is a place for developers, not dickheads

Fully agree


> so get a life

Already done


> and get the f**k out of here.

I will choose myself where I would like to be. When I need anyone's advice I will ask for that somewhere else, because `This is a place for developers, not dickheads`

**Comment by TitanFighter** [comment]
Can anyone check the next:
```
    <youtube
      ref="youtube"
      // ...
      :player-vars="playerVars"
    />

    playerVars: {
      // ...
      origin: window.location.origin // or http(S)://your.domain.com
    }
```

Taken from [here](https://github.com/oskarrough/ember-youtube#youtube-player-options).

**Comment by michaelfeinbier** [comment]
Adding the `origin: window.location.origin` to the playerVars as suggested by @TitanFighter worked for me (tested in Chrome 71). Thanks!

**Comment by eskalation** [comment]
I am currently suck on this issue as well, adding window.location.origin as the origin doesn't fix it here, my guess is that i is because the iframe links to https, whereas my domain is on regular http. Would it be possible to add support for changing the iframe from https to http, if needed?

**Comment by rene-dohan** [comment]
I think this can be fixed like this in source of vue-youtube:

https://www.youtube.com/embed/HIbAz29L-FA?modestbranding=1&playsinline=0&showinfo=0&enablejsapi=1&origin=https%3A%2F%2Fintercoin.org&widgetid=1

Note the "origin" component, as well as "enablejsapi=1". The origin must match what your domain is, and then it will be whitelisted and work.

**Comment by anteriovieira** [comment]
close from https://github.com/anteriovieira/vue-youtube/pull/34

**Comment by kms-rscholz** [comment]
@anteriovieira still not solved for me! happy to provide any infos you may need for debugging!

**Comment by jjangga0214** [comment]
@anteriovieira Still not solved.
```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.youtube.com’) does not match the recipient window’s origin (‘http://localhost:8080’).
```

**Comment by kms-rscholz** [comment]
@jjangga0214 does the error persist on a server (as opposed to your local dev environment)?

**Comment by Erutan409** [comment]
@kms-rscholz It does in my case.  The server I'm developing is SSL, too.

**Comment by kms-rscholz** [comment]
@Erutan409 jup, thought it was solved in our production build, but the error still occurs for us too:
https://new.kms-team.com/en

**Comment by kms-rscholz** [comment]
@anteriovieira Might be worth reopening this issue until a fix can be found!

**Comment by bjcooper** [comment]
@anteriovieira ,this is still happening for me on 1.4.0 as well, unfortunately. Both locally in development and on a production server with SSL.

**Comment by zmts** [comment]
I use native youtube iframe and it works for me
```
<iframe
        v-if="isYoutubeLink"
        frameborder="0"
        width="100%"
        :height="playerHeight"
        :src="`https://www.youtube.com/embed/${videoId}`"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
</iframe>
```
