### ISSUE TITLE
Having trouble passing the related videos tag with the player vars

### ISSUE THREAD

**Issue by wirsing** [anteriovieira/vue-youtube#14]
observed: youtube(video-id="foo" player-vars="{ rel: 0}" ref="youtube") somehow does not add the rel=0 attribute to the iframe. 

expected: "rel=0" would be added as attribute once passed as player var.

**Comment by anteriovieira** [comment]
[Live demo](https://codesandbox.io/s/jmr9nn90y) :smile_cat:
