### ISSUE TITLE
Acces to getDuration()

### ISSUE THREAD

**Issue by moutz** [anteriovieira/vue-youtube#15]
Hello,

Thank you for your work on this component.
I try to access to getDuration(), according to the Youtube API. But i can not get the value, it returns me a function as a string. When I try to log I get a ReactiveGetter().
I made a demo here : https://codesandbox.io/s/9vwmmz30r

M.

**Comment by anteriovieira** [comment]
Hi @moutz , try https://codesandbox.io/s/olp2824nj9
