### ISSUE TITLE
How to set the size of the Iframe?

### ISSUE THREAD

**Issue by pushpitab** [anteriovieira/vue-youtube#16]
Hi ,

How to can i set the size of the Iframe?
I have to make it responsive  and the following does not work. Can someone help?
  **v-layout row>
            v-flex xs12 sm6 offset-sm3>
                <youtube  :video-id="getId"  ref="youtube" @playing="playing"></youtube>
            v-flex>
          v-layout>**

**Comment by TitanFighter** [comment]
Something like this:
```
<template>
  <youtube :video-id="youtubeId"
           :width="youtubeWidth" :height="youtubeHeight"
           :player-vars="playerVars"
           ref="youtube">
  </youtube>
</template>

<script>
  export default {
    name: 'MyYoutubePlayer',

    data () {
      return {
        playerVars: {
          autoplay: 1
        },

        youtubeId: 'Hh-0y8Qe0Sw',

        youtubeWidth: 640,
        youtubeHeight: 360
      }
    }
</script>
```

**Comment by pushpitab** [comment]
This just set width and height for all devices same, I wanted to make it flex responsive, generally wrapping the component under flex element it helps to be responsive.

**Comment by anteriovieira** [comment]
Hi @pushpitab , try
`
[Demo](https://codesandbox.io/s/9o04vl5rmo)

````vue
<template>
	<div id="app">
		<youtube video-id="BBJa32lCaaY" class="video" />
	</div>
</template>

<script>
	export default {
    name: 'app'
  }
</script>

<style>
#app {
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 56.25%;
}
.video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
</style>
````

**Comment by pushpitab** [comment]
it works thanks so much :)
