### ISSUE TITLE
how to use https version of youtube.com/frame_api

### ISSUE THREAD

**Issue by xerosanyam** [anteriovieira/vue-youtube#19]

**Comment by monstromatic** [comment]
+1
Got the error: Failed to execute 'postMessage' on 'DOMWindow': The target origin provided...

**Comment by anteriovieira** [comment]
closes from https://github.com/anteriovieira/vue-youtube/pull/34

**Comment by anteriovieira** [comment]
closed this in https://github.com/anteriovieira/vue-youtube/pull/34
