### ISSUE TITLE
 How to know if the URL or ID is invalid

### ISSUE THREAD

**Issue by waittinghsu** [anteriovieira/vue-youtube#20]
sorry i have a question
when i change videoId , just saw cued event and get jpg error
How do I know in advance that the URL is invalid before play video?

**Comment by TitanFighter** [comment]
Hi @waittinghsu 
Check [this](https://stackoverflow.com/a/31742587/4992248) and [this](https://stackoverflow.com/a/46634346/4992248).

**Comment by waittinghsu** [comment]
thx >"<
