### ISSUE TITLE
Unable to post message to https://www.youtube.com.

### ISSUE THREAD

**Issue by lukaszflorczak** [anteriovieira/vue-youtube#25]
Hi. I'm testing your component. I found this error in browser console:

```Unable to post message to https://www.youtube.com. Recipient has origin http://localhost:8081.```

Could you explain what it means and how to fix it? What „message” does it want to post?

**Comment by albertoannunziata90** [comment]
I believe this is an issue with the source origin being http meanwhile the target is https

**Comment by anteriovieira** [comment]
Closed this in https://github.com/anteriovieira/vue-youtube/pull/34
