### ISSUE TITLE
Lazy loading for YouTube video?

### ISSUE THREAD

**Issue by koddr** [anteriovieira/vue-youtube#3]
Hello.

Would be nice to add lazy loading for YouTube video. It's the best practice on mobile devices and people who use low signal Internet. And, of course, for Google Search, because page loaded faster.

For example, something like this: https://codepen.io/tutsplus/pen/RRVRro

**Comment by anteriovieira** [comment]
Hi @koddr , thanks for the suggestion. I'll start the implementation as soon as I have time.
If you have an idea how to implement please feel free to send a pull request :wink:

**Comment by Psychokrameur** [comment]
Maybe can be inspired by : https://github.com/andrewvasilchuk/vue-lazy-youtube-video
