### ISSUE TITLE
Play video asynchronously when changing video id

### ISSUE THREAD

**Issue by leandromatos-hotmart** [anteriovieira/vue-youtube#31]
How to play an video after the player is ready?

My app has buttons for load different videos in an unique instance of vue-youtube. I need click in some button and after player loaded,  i need play this video.

**Comment by TitanFighter** [comment]
Show demo, for example using code sandbox service and I will fix it.

**Comment by leandromatos-hotmart** [comment]
Hey @TitanFighter, i created an sample code here https://codesandbox.io/embed/codesandboxnuxt-gum2y

**Comment by TitanFighter** [comment]
You have such lines inside `selectEdition` method:
```
// Play video after player loaded...
this.playVideo();
```
Change them to:
```
      this.$nextTick(function() {
        // Play video after player loaded...
        this.playVideo();
      });
```
`nextTick` [details](https://vuejs.org/v2/api/#Vue-nextTick)

**Comment by leandromatos-hotmart** [comment]
@TitanFighter, doesn't work. Maybe because the nextTick run before the video player load a new video.

Ideally, each time you load a video, the ready event is triggered,  but  today this event only fires when you load the first video.

**Comment by TitanFighter** [comment]
Here is the [example](https://codesandbox.io/s/olii6). Without nextTick when you click for example 2017 just picture is changed (video does not start automatically), but with nextTick when you click any year, video is changed and started automatically. Is it not what you need? Does not work?

**Comment by leandromatos-hotmart** [comment]
Strange, I just tested again and it worked. What I noticed is that by clicking on a year, a small delay occurs between the player having loaded the video and it starts playing.

Thanks
