### ISSUE TITLE
All functions seem to return pending promises that never resolve

### ISSUE THREAD

**Issue by LeszekKicior** [anteriovieira/vue-youtube#39]
Hi,

I'm trying to use this wrapper in my new project, however I've run into a problem - the player itself works exactly as intended, but I can't control it in code.

Extremely simple example:
```
      <youtube :video-id="videoId" ref="youtube" width="600" height="400" :player-vars="playerVars"></youtube>
      <button @click="play">PLAY</button>
```

```
methods: {
   play () {
     this.$refs.youtube.player.playVideo()
   }
}
```

The player itself works - I can click it to start the video, skip around, et cetera. However, the `play()` method does nothing. All it returns is [an empty, pending promise](https://i.imgur.com/LQUpWGP.png)

Have I missed something? I'm assuming that were the promises to resolve, it would allow me to control the player.

**Comment by TitanFighter** [comment]
Everything works -> https://codesandbox.io/s/vue-template-v9sv0

**Comment by LeszekKicior** [comment]
You're right, it would seem the problems lies with my browser - Your example didn't work either, until I switched to a different one. The problem might be with one of the installed extensions, or browser config, or a myriad other things, but it won't follow me into production.
