### ISSUE TITLE
Add nocookies prop to add the host option “https://www.youtube-nocookie.com”

### ISSUE THREAD

**Issue by pheadeaux** [anteriovieira/vue-youtube#41]
# Problem
To use Youtube GDPR compliant, I don't want to use the default config of the youtube player. Rather use the nocookie-domain:

# direct implementation:

```JS
var player;
var tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
      	var firstScriptTag = document.getElementsByTagName('script')[0];
      	firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

player = new YT.Player('player1', {
	    wmode: 'transparent',
            host: 'https://www.youtube-nocookie.com',
	    playerVars:{
		   wmode: 'transparent',
		   showinfo:0,
		   autohide:1,
            },
	  videoId: YOUR_VID_ID,
	  events: {
		  'onReady': onPlayerReady
		}
        });
```

[https://portalzine.de/dev/api/youtube-iframe-api-and-cookieless-domain-solution-gdpr-dsgvo/](https://portalzine.de/dev/api/youtube-iframe-api-and-cookieless-domain-solution-gdpr-dsgvo/)

# How to fix?

Add a new prop `nocookie` boolean flag and set the host accordingly.

**Comment by anteriovieira** [comment]
Thanks @pheadeaux
