### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by eduardocmoreno** [anteriovieira/vue-youtube#5]
Antério, very nice plugin! I'd like to use a playlist ID instead of video ID, whats the way?

Antério, muito bom seu plugin, estou utilizando ele no momento, porém gostaria de saber se é possível usar uma ID de playlist.

**Comment by anteriovieira** [comment]
Hi @eduardocmoreno , the component does not work with list of videos, just a video. You will have to develop your own playlist component and then integrate the vue-youtube component.

But it does not seem complicated to me.

**Comment by eduardocmoreno** [comment]
Ok @anteriovieira, thx for reply.

**Comment by digitalfrost** [comment]
Hi @eduardocmoreno - the component works fine if you pass a valid value for **playlist** in **playervars** as per the YouTube IFrame API Documentation:
https://developers.google.com/youtube/player_parameters?playerVersion=HTML5

**Comment by anteriovieira** [comment]
[Example with playlist](https://codesandbox.io/s/n938n3953p)

Thank you @digitalfrost
