### ISSUE TITLE
Option to use youtube embed with privacy enhanced mode (-nocookie youtube)

### ISSUE THREAD

**Issue by henryz00** [anteriovieira/vue-youtube#55]
Currently all the plays on the embedded youtube video will get tracked and stored in user's youtube watch history, this might not be an intended behaviour of many apps.

Adding an option to disable this would be awesome, and I think this can be implemented simply by adding `-nocookie` to the youtube embed URL, such as `https://www.youtube-nocookie.com/embed/O17OWyx08Cg`.

More about this mode can be found [here](https://support.google.com/youtube/answer/171780?hl=en-GB)

**Comment by jamalroger** [comment]
add host to player-vars porps
```js
<youtube  ref="youtube" :video-id="video" :player-vars="{host:'www.youtube-nocookie.com'}"></youtube>

```

**Comment by henryz00** [comment]
> add host to player-vars porps
> 
> ```js
> <youtube  ref="youtube" :video-id="video" :player-vars="{host:'www.youtube-nocookie.com'}"></youtube>
> ```

Thanks! Unfortunately, that did not work for me. It seems that `host` para should be at the same level as `player-vars` when passed to the actual youtube player.

**Comment by henryz00** [comment]
Actually, after digging through the source code, turns out this function is already implemented 😅 . Just set `nocookie` prop to `true`, the host param will be changed to `www.youtube-nocookie.com`.
