### ISSUE TITLE
Should not warn if valid playlist

### ISSUE THREAD

**Issue by digitalfrost** [anteriovieira/vue-youtube#6]
Should not raise 

```
 [Vue warn]: Missing required prop: "videoId"
```

if **playerVars** has a valid value for **playlist** .

**Comment by anteriovieira** [comment]
Thanks @digitalfrost , it is was fixed in v1.2.5 version.

[Example here](https://codesandbox.io/s/n938n3953p)

**Comment by digitalfrost** [comment]
Thank you. 
I have upgraded from v1.2.2  to v1.2.5, the fix works for me.
Thanks for being so quick with the new release.
