### ISSUE TITLE
How to adapt vue-youtube to use with Vuex

### ISSUE THREAD

**Issue by rjapur** [anteriovieira/vue-youtube#8]
Hi, i'm using vuex in my project and but i can't make your component work with it, i always get the issue 'Unknown custom element: <youtube> - did you register the component correctly? For recursive components, make sure to provide the "name" option.'

Do you a have a solution for that?

**Comment by anteriovieira** [comment]
Hi @rjapur , I do not see anything that can prevent it from working with vuex.

Can you provide an example of your code?

**Comment by biwerr** [comment]
Maybe it helps ...
```
<template>
    <div class="mycomponent">
          <youtube .... ></youtube>
    </div>
</template>
<script>

    import { Youtube } from 'vue-youtube';
   
    export default {
        name: "yourcomponent",
        components: {
            Youtube
        },
     ....
</script>
```
